export const TRANSLATIONS = {
    EN: {
        PLAY: "PLAY",
        SETTINGS: "SETTINGS",
        CREDITS: "CREDITS",
        QUIT: "QUIT",
        BACK: "BACK",
        SAVE_CHANGES_PROMPT: "Save changes before leaving?",
        SAVE_CHANGES_DESCRIPTION: "You have unsaved changes. Would you like to save before leaving?",
        YES: "YES",
        NO: "NO",
        CANCEL: "CANCEL",
        LANGUAGE: "LANGUAGE",
        VOLUME: "VOLUME",
        DIFFICULTY: "DIFFICULTY",
        MODIFIERS: "MODIFIERS",
        DAILY_CHALLENGE: "DAILY CHALLENGE",
        MULTIPLAYER: "MULTIPLAYER (BETA)",
        TUTORIAL: "PLAY TUTORIAL",
        EDITOR: "LEVEL EDITOR",
        JUKEBOX: "JUKEBOX",
        PRACTICE: "PRACTICE MODE",
        TOURNAMENT: "TOURNAMENT",
        CAMPAIGN: "CAMPAIGN MODE",
        CLOUD_SYNC: "CLOUD SYNC",
        SOCIAL: "SOCIAL",
        ENTER_VR: "ENTER VR",
        SPECTATE: "SPECTATE",
        VISUALIZER: "VISUALIZER MODE",
        RHYTHM_EDITOR: "RHYTHM EDITOR",
        GAME_MODIFIERS: "GAME MODIFIERS",
        MIRROR_MODE: "MIRROR MODE",
        COLORBLIND_MODE: "COLORBLIND MODE",
        ZEN_MODE: "ZEN MODE",
        FOCUS_MODE: "FOCUS MODE",
        CALIBRATION: "CALIBRATION WIZARD",
        REPLAY_EDITOR: "REPLAY EDITOR",
        THEME: "THEME",
        AVATAR: "AVATAR",
        CUSTOMIZE: "CUSTOMIZE",
        WORKSHOP: "WORKSHOP",
        DLC_PACKS: "DLC PACKS",
        DAILY_QUESTS: "DAILY QUESTS",
        QUEST_SCORE: "Score {0} points in one game",
        QUEST_COMBO: "Reach a combo of {0}",
        QUEST_PERFECT: "Get {0} Perfects in one game",
        QUEST_PLAY: "Play {0} songs",
        CLAIM: "CLAIM",
        BUY: "BUY",
        OWNED: "OWNED",
        PACK_UNLOCKED: "Pack unlocked!",
        TAB_PLAY: "PLAY",
        TAB_TOOLS: "TOOLS",
        TAB_COMMUNITY: "COMMUNITY",
        TAB_SYSTEM: "SYSTEM",
        TAB_GENERAL: "GENERAL",
        TAB_AUDIO: "AUDIO",
        TAB_GAMEPLAY: "GAMEPLAY",
        TAB_APPEARANCE: "APPEARANCE",
        DOWNLOAD: "DOWNLOAD",
        AUTHOR: "AUTHOR",
        RATING: "RATING",
        SEARCH: "SEARCH",
        ON: "ON",
        OFF: "OFF",
        CLOSE: "CLOSE",
        FRIENDS_LIST: "FRIENDS LIST",
        DAILY_REWARD: "DAILY REWARD",
        COLLECT: "COLLECT",
        CREDITS_ADDED: "CREDITS ADDED",
        USERNAME: "USERNAME",
        GLOBAL_VOLUME: "GLOBAL VOLUME",
        AUDIO_OFFSET: "AUDIO OFFSET",
        NOTE_SKIN: "NOTE SKIN",
        NOTE_SIZE: "NOTE SIZE",
        PARTICLE_SHAPE: "PARTICLE SHAPE",
        DYNAMIC_DIFFICULTY: "DYNAMIC DIFFICULTY",
        NOT_ENOUGH_CREDITS: "Not enough credits!",
        SONG_LOADED: "Custom song loaded!",
        LEVEL: "LEVEL",
        XP: "XP",
        CONNECTING: "CONNECTING...",
        UPLOADING: "UPLOADING...",
        SYNC_COMPLETE: "SYNC COMPLETE",
        SCORE: "SCORE",
        COMBO: "COMBO",
        INTEGRITY: "INTEGRITY",
        SELECT_SONG_FOR_MULTIPLAYER: "Select a song for multiplayer",
        NEWS_TICKER_ITEMS: "BREAKING: SYSTEM BREACH DETECTED IN SECTOR 7 // TOP PLAYER 'CYPHER' REACHES 1,000,000 PTS // NEW SONG PACK 'NEON NIGHTMARE' AVAILABLE // REMINDER: DO NOT TRUST THE AI // DAILY CHALLENGE RESET IN 04:00:00 // "
    },
    FR: {
        PLAY: "JOUER",
        SETTINGS: "PARAMÈTRES",
        CREDITS: "CRÉDITS",
        QUIT: "QUITTER",
        BACK: "RETOUR",
        SAVE_CHANGES_PROMPT: "Sauvegarder les modifications avant de quitter ?",
        SAVE_CHANGES_DESCRIPTION: "Vous avez des modifications non sauvegardées. Voulez-vous enregistrer avant de quitter ?",
        YES: "OUI",
        NO: "NON",
        CANCEL: "ANNULER",
        LANGUAGE: "LANGUE",
        VOLUME: "VOLUME",
        DIFFICULTY: "DIFFICULTÉ",
        MODIFIERS: "MODIFICATEURS",
        DAILY_CHALLENGE: "DÉFI QUOTIDIEN",
        MULTIPLAYER: "MULTIJOUEUR (BETA)",
        TUTORIAL: "TUTORIEL",
        EDITOR: "ÉDITEUR DE NIVEAU",
        JUKEBOX: "JUKEBOX",
        PRACTICE: "ENTRAÎNEMENT",
        TOURNAMENT: "TOURNOI",
        CAMPAIGN: "CAMPAGNE",
        CLOUD_SYNC: "CLOUD SYNC",
        SOCIAL: "SOCIAL",
        ENTER_VR: "MODE VR",
        SPECTATE: "SPECTATEUR",
        VISUALIZER: "VISUALISEUR",
        RHYTHM_EDITOR: "ÉDITEUR RYTHME",
        GAME_MODIFIERS: "MODIFICATEURS",
        MIRROR_MODE: "MODE MIROIR",
        COLORBLIND_MODE: "MODE DALTONIEN",
        ZEN_MODE: "MODE ZEN",
        FOCUS_MODE: "MODE FOCUS",
        CALIBRATION: "CALIBRATION",
        REPLAY_EDITOR: "ÉDITEUR REPLAY",
        THEME: "THÈME",
        AVATAR: "AVATAR",
        CUSTOMIZE: "PERSONNALISER",
        WORKSHOP: "ATELIER",
        DLC_PACKS: "PACKS DLC",
        DAILY_QUESTS: "QUÊTES DU JOUR",
        QUEST_SCORE: "Score de {0} points en une partie",
        QUEST_COMBO: "Atteindre un combo de {0}",
        QUEST_PERFECT: "Obtenir {0} Parfaits en une partie",
        QUEST_PLAY: "Jouer {0} chansons",
        CLAIM: "RÉCLAMER",
        BUY: "ACHETER",
        OWNED: "POSSÉDÉ",
        PACK_UNLOCKED: "Pack débloqué !",
        TAB_PLAY: "JOUER",
        TAB_TOOLS: "OUTILS",
        TAB_COMMUNITY: "COMMUNAUTÉ",
        TAB_SYSTEM: "SYSTÈME",
        TAB_GENERAL: "GÉNÉRAL",
        TAB_AUDIO: "AUDIO",
        TAB_GAMEPLAY: "JEU",
        TAB_APPEARANCE: "APPARENCE",
        DOWNLOAD: "TÉLÉCHARGER",
        AUTHOR: "AUTEUR",
        RATING: "NOTE",
        SEARCH: "RECHERCHER",
        ON: "ACTIVÉ",
        OFF: "DÉSACTIVÉ",
        CLOSE: "FERMER",
        FRIENDS_LIST: "LISTE D'AMIS",
        DAILY_REWARD: "RÉCOMPENSE DU JOUR",
        COLLECT: "COLLECTER",
        CREDITS_ADDED: "CRÉDITS AJOUTÉS",
        USERNAME: "PSEUDO",
        GLOBAL_VOLUME: "VOLUME GLOBAL",
        AUDIO_OFFSET: "DÉCALAGE AUDIO",
        NOTE_SKIN: "APPARENCE NOTES",
        NOTE_SIZE: "TAILLE NOTES",
        PARTICLE_SHAPE: "FORME PARTICULES",
        DYNAMIC_DIFFICULTY: "DIFFICULTÉ DYNAMIQUE",
        NOT_ENOUGH_CREDITS: "Crédits insuffisants !",
        SONG_LOADED: "Chanson chargée !",
        LEVEL: "NIVEAU",
        XP: "XP",
        CONNECTING: "CONNEXION...",
        UPLOADING: "ENVOI...",
        SYNC_COMPLETE: "SYNCHRO TERMINÉE",
        SCORE: "SCORE",
        COMBO: "COMBO",
        INTEGRITY: "INTÉGRITÉ",
        SELECT_SONG_FOR_MULTIPLAYER: "Sélectionnez une chanson pour le multijoueur",
        NEWS_TICKER_ITEMS: "DERNIÈRE MINUTE : BRÈCHE SYSTÈME DÉTECTÉE SECTEUR 7 // TOP PLAYER 'CYPHER' ATTEINT 1 000 000 PTS // NOUVEAU PACK 'NEON NIGHTMARE' DISPONIBLE // RAPPEL : NE FAITES PAS CONFIANCE À L'IA // DÉFI QUOTIDIEN REPART DANS 04:00:00 // ",
        BOSS_BATTLE_ACTIVATED: "Boss activé !",
        LEVEL_COMPLETED: "Niveau terminé !"
    },
    JP: {
        PLAY: "プレイ",
        SETTINGS: "設定",
        CREDITS: "クレジット",
        QUIT: "終了",
        BACK: "戻る",
        SAVE_CHANGES_PROMPT: "変更を保存してから離れますか？",
        SAVE_CHANGES_DESCRIPTION: "保存されていない変更があります。離れる前に保存しますか？",
        YES: "はい",
        NO: "いいえ",
        CANCEL: "キャンセル",
        LANGUAGE: "言語",
        VOLUME: "音量",
        DIFFICULTY: "難易度",
        MODIFIERS: "モディファイア",
        DAILY_CHALLENGE: "デイリーチャレンジ",
        MULTIPLAYER: "マルチプレイ (ベータ)",
        TUTORIAL: "チュートリアル",
        EDITOR: "レベルエディタ",
        JUKEBOX: "ジュークボックス",
        PRACTICE: "練習モード",
        TOURNAMENT: "トーナメント",
        CAMPAIGN: "キャンペーン",
        CLOUD_SYNC: "クラウド同期",
        SOCIAL: "ソーシャル",
        ENTER_VR: "VRモード",
        SPECTATE: "観戦",
        VISUALIZER: "ビジュアライザー",
        RHYTHM_EDITOR: "リズムエディタ",
        GAME_MODIFIERS: "ゲーム設定",
        MIRROR_MODE: "ミラーモード",
        COLORBLIND_MODE: "色覚サポート",
        ZEN_MODE: "禅モード",
        FOCUS_MODE: "フォーカスモード",
        CALIBRATION: "判定調整",
        REPLAY_EDITOR: "リプレイ編集",
        THEME: "テーマ",
        AVATAR: "アバター",
        CUSTOMIZE: "カスタマイズ",
        WORKSHOP: "ワークショップ",
        DLC_PACKS: "DLCパック",
        DAILY_QUESTS: "デイリークエスト",
        QUEST_SCORE: "1ゲームで{0}点を獲得",
        QUEST_COMBO: "{0}コンボ達成",
        QUEST_PERFECT: "1ゲームで{0}パーフェクト",
        QUEST_PLAY: "{0}曲プレイする",
        CLAIM: "受け取る",
        BUY: "購入",
        OWNED: "所有済み",
        PACK_UNLOCKED: "パック解除！",
        TAB_PLAY: "プレイ",
        TAB_TOOLS: "ツール",
        TAB_COMMUNITY: "コミュニティ",
        TAB_SYSTEM: "システム",
        TAB_GENERAL: "一般",
        TAB_AUDIO: "オーディオ",
        TAB_GAMEPLAY: "ゲームプレイ",
        TAB_APPEARANCE: "外観",
        DOWNLOAD: "ダウンロード",
        AUTHOR: "作者",
        RATING: "評価",
        SEARCH: "検索",
        ON: "オン",
        OFF: "オフ",
        CLOSE: "閉じる",
        FRIENDS_LIST: "フレンドリスト",
        DAILY_REWARD: "デイリー報酬",
        COLLECT: "受け取る",
        CREDITS_ADDED: "クレジット追加",
        USERNAME: "ユーザー名",
        GLOBAL_VOLUME: "全体音量",
        AUDIO_OFFSET: "音声ズレ調整",
        NOTE_SKIN: "ノートスキン",
        NOTE_SIZE: "ノートサイズ",
        PARTICLE_SHAPE: "パーティクル形状",
        DYNAMIC_DIFFICULTY: "動的難易度",
        NOT_ENOUGH_CREDITS: "クレジット不足！",
        SONG_LOADED: "カスタム曲を読み込みました！",
        LEVEL: "レベル",
        XP: "XP",
        CONNECTING: "接続中...",
        UPLOADING: "アップロード中...",
        SYNC_COMPLETE: "同期完了",
        SCORE: "スコア",
        COMBO: "コンボ",
        INTEGRITY: "インテグリティ",
        SELECT_SONG_FOR_MULTIPLAYER: "マルチプレイヤー用の曲を選択",
        NEWS_TICKER_ITEMS: "速報：セクター7でシステム侵害発生 // トッププレイヤー『CYPHER』が1,000,000点達成 // 新曲パック『NEON NIGHTMARE』登場 // AIを信用するな // デイリーチャレンジまで04:00:00 // ",
        BOSS_BATTLE_ACTIVATED: "ボス出現！",
        LEVEL_COMPLETED: "レベル完了！"
    }
};

export class Localization {
    constructor(lang = 'EN') {
        this.lang = lang;
    }
    
    setLanguage(lang) {
        if (TRANSLATIONS[lang]) this.lang = lang;
    }
    
    get(key) {
        return TRANSLATIONS[this.lang][key] || key;
    }
}
